ami_id = "ami-"  #update ami
instance_type = "t2.micro"     
vpc_name = "my-tf-vpc"
cidr_block = "10.0.0.0/16"
enable_dns_support = true
enable_dns_hostnames = true
availability_zones      = ["eu-east-1a", "eu-east-1b"]
public_subnet_cidr_blocks = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidr_blocks = ["10.0.3.0/24", "10.0.4.0/24"]
enable_nat_gateway = true
enable_vpn_gateway = true